# Generated by Django 2.1.2 on 2018-10-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='title',
        ),
    ]
