# Generated by Django 2.1.2 on 2018-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_uploadfile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
