# Generated by Django 2.1.2 on 2018-10-22 23:35

import django.core.files.storage
from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/harrison/www/uploads/'), upload_to=webapp.models.default_upload_path, verbose_name='Upload File')),
            ],
        ),
    ]
