# Generated by Django 2.1.2 on 2018-10-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181023_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
